site_name: Analysis Results Standard (ARS)
site_url: https://cdisc-org.github.io/analysis-results-standard/
nav:
    - Home: index.md
    #- About: about.md
plugins:
    - search
    - mermaid2:
        version: 9.4.0
extra_javascript:
    - https://cdn.jsdelivr.net/npm/svg-pan-zoom-container@0.6.1
docs_dir: project/docs
site_dir: docs